bits 16
cpu 8086
org 0x8000

%include "stage2/layout.inc"
%include "stage2/core.inc"
%include "stage2/hal_display.inc"
%include "stage2/ui_core.inc"
%include "stage2/hal_detect.inc"
%include "stage2/ui_menu.inc"
%include "stage2/hal_nic.inc"
%include "stage2/net_phase.inc"
%include "stage2/config.inc"
%include "stage2/fs.inc"
%include "stage2/nic.inc"
%include "stage2/net_tx.inc"
%include "stage2/net_rx.inc"
%include "stage2/ui.inc"
%include "stage2/data.inc"
