#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SECTOR = 512
CORE_LOAD_ADDR = 0x1000
HELPER_LABELS = (
    "net_fail_al",
    "parse_tcp_payload",
    "c503_select_dp8390",
)


def _eval(expr: str, consts: dict[str, int]) -> int:
    py = expr.replace("/", "//")
    return int(eval(py, {"__builtins__": {}}, consts))


def parse_equates(paths: list[Path]) -> dict[str, int]:
    lines: list[str] = []
    for path in paths:
        lines.extend(path.read_text().splitlines())
    consts: dict[str, int] = {}
    while True:
        before = len(consts)
        for raw in lines:
            line = raw.split(";", 1)[0].strip()
            match = re.match(r"^(\w+)\s+equ\s+(.+)$", line)
            if not match or match.group(1) in consts:
                continue
            try:
                consts[match.group(1)] = _eval(match.group(2).strip(), consts)
            except Exception:
                continue
        if len(consts) == before:
            return consts


def parse_listing_labels(listing: Path) -> dict[str, int]:
    lines = listing.read_text(errors="replace").splitlines()
    labels: dict[str, int] = {}
    for index, line in enumerate(lines):
        match = re.search(r"<\d+>\s+(\w+):\s*$", line)
        if not match:
            continue
        name = match.group(1)
        if name not in HELPER_LABELS:
            continue
        for code in lines[index + 1 :]:
            code_match = re.search(r"\s[0-9]+\s+([0-9A-Fa-f]{8})\s", code)
            if code_match:
                labels[name] = CORE_LOAD_ADDR + int(code_match.group(1), 16)
                break
    missing = sorted(set(HELPER_LABELS) - set(labels))
    if missing:
        raise SystemExit(f"{listing}: missing helper labels: {', '.join(missing)}")
    return labels


def write_abi(path: Path, consts: dict[str, int], labels: dict[str, int]) -> None:
    lines = ["; Generated by tools/build-nic-driver.py; do not edit.\n"]
    for name in sorted(consts):
        lines.append(f"{name} equ 0x{consts[name]:x}\n")
    for name in HELPER_LABELS:
        lines.append(f"{name} equ 0x{labels[name]:x}\n")
    path.write_text("".join(lines))


def write_wrapper(path: Path, abi: Path, source: Path, family_mask: int) -> None:
    rel_abi = abi.as_posix()
    rel_source = source.as_posix()
    path.write_text(
        "\n".join(
            (
                "bits 16",
                "cpu 8086",
                f'%include "{rel_abi}"',
                "org nic_driver_slot",
                '%include "core/nic_ring.inc"',
                "driver_start:",
                "%define DRIVER_BASE driver_start",
                f"%define DRIVER_FAMILY_MASK 0x{family_mask:x}",
                f'%include "{rel_source}"',
                "%undef DRIVER_FAMILY_MASK",
                "%undef DRIVER_BASE",
                "driver_noop:",
                "    ret",
                "driver_no_fallback:",
                "    stc",
                "    ret",
                "driver_end:",
                "%if (driver_end - driver_start) > nic_driver_slot_len",
                '%error "NIC driver exceeds active-driver slot"',
                "%endif",
                "times nic_driver_slot_len - (driver_end - driver_start) db 0",
                "",
            )
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--listing", required=True, type=Path)
    parser.add_argument("--layout", default=ROOT / "targets/ibm_pc_5150/boot/core/layout.inc", type=Path)
    parser.add_argument("--data", default=ROOT / "targets/ibm_pc_5150/boot/core/data.inc", type=Path)
    parser.add_argument("--build-dir", required=True, type=Path)
    parser.add_argument("--family-mask", required=True, type=lambda value: int(value, 0))
    args = parser.parse_args()

    args.build_dir.mkdir(parents=True, exist_ok=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    abi = args.build_dir / "nic-driver-abi.inc"
    wrapper = args.build_dir / f"{args.output.stem.lower()}-driver-wrapper.asm"
    write_abi(abi, parse_equates([args.layout, args.data]), parse_listing_labels(args.listing))
    write_wrapper(wrapper, abi, args.source, args.family_mask)
    subprocess.run(
        [
            "nasm",
            "-Itargets/ibm_pc_5150/boot/",
            f"-I{args.build_dir}/",
            "-f",
            "bin",
            "-o",
            str(args.output),
            str(wrapper),
        ],
        cwd=ROOT,
        check=True,
    )
    size = args.output.stat().st_size
    if size != SECTOR:
        raise SystemExit(f"{args.output}: expected one sector, got {size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
