#!/usr/bin/env python3
"""Generate RSA-2048 public-key data blocks for the 286 secure tier.

Build 13 no longer bakes the provider leaf into SEED.SYS. Standard images ship the current
leaf as SEED/LEAF.DER; the 286 verifies that DER against the baked WR1 anchor, then adopts
the leaf key into runtime-only RSA workspace before the in-race ServerKeyExchange verify.

The production use of this script is therefore the durable WR1 anchor:

  python3 tools/gen-rsa-pinned-key.py --mode anchor --pem openai-chain.pem \
      --out targets/ibm_pc_5150/boot/core/rsa_anchor_wr1.inc
  python3 tools/gen-rsa-pinned-key.py --selftest      # prove the Montgomery math vs the bench

The default leaf mode is retained only for old rotation/debug notes. --mode anchor pins the
ISSUING CA (GTS WR1) key -- the durable anchor for silent auto-recertify. The off-race X.509
chain-verify (tools/x509/x509_verify.py is the offline oracle for it)
checks a freshly-rotated leaf against this anchor before adopting it, so a leaf rotation needs no
rebuild while trust still derives from a key we already hold. WR1 lives years; re-pin only on WR1
rotation. cert[1] of the -showcerts chain is the issuer.
"""
from __future__ import annotations
import argparse
import subprocess
import sys

WORDS = 128                 # 2048-bit operands, 16-bit little-endian limbs
NBITS = WORDS * 16          # 2048
R = 1 << NBITS              # Montgomery radix


def to_words(value: int) -> list[int]:
    return [(value >> (16 * i)) & 0xFFFF for i in range(WORDS)]


def mont_params(n: int) -> tuple[int, int]:
    if n.bit_length() != 2048:
        raise SystemExit(f"modulus is {n.bit_length()} bits, expected 2048 (RSA-2048 leaf)")
    if n % 2 == 0:
        raise SystemExit("modulus is even -- not an RSA modulus")
    n0inv = (-pow(n, -1, 1 << 16)) % (1 << 16)   # -N^-1 mod 2^16  (CIOS reduction multiplier)
    r2 = pow(R, 2, n)                            # R^2 mod N
    return n0inv, r2


def bignum_lines(name: str, value: int, per_line: int = 8) -> str:
    w = to_words(value)
    out = [f"{name}:"]
    for i in range(0, WORDS, per_line):
        out.append("    dw " + ",".join(str(x) for x in w[i:i + per_line]))
    return "\n".join(out) + "\n"


def nth_cert_pem(pem_path: str, index: int) -> str:
    """Return the Nth certificate (0 = leaf, 1 = issuer/WR1, ...) from a -showcerts chain as PEM."""
    blocks, cur, keep = [], [], False
    for line in open(pem_path).read().splitlines():
        if "BEGIN CERTIFICATE" in line:
            keep, cur = True, [line]
            continue
        if "END CERTIFICATE" in line:
            cur.append(line)
            blocks.append("\n".join(cur) + "\n")
            keep = False
            continue
        if keep:
            cur.append(line)
    if index >= len(blocks):
        raise SystemExit(f"chain has {len(blocks)} cert(s); no cert at index {index} "
                         f"(need the issuer cert in the chain — re-capture with -showcerts)")
    return blocks[index]


def _openssl_x509(pem_text: str, *flags: str) -> str:
    out = subprocess.run(["openssl", "x509", "-noout", *flags],
                         input=pem_text, capture_output=True, text=True, check=True).stdout.strip()
    return out


def modulus_from_pem_text(pem_text: str) -> int:
    out = _openssl_x509(pem_text, "-modulus")
    if not out.startswith("Modulus="):
        raise SystemExit(f"unexpected openssl output: {out[:40]!r}")
    return int(out[len("Modulus="):], 16)


def cert_meta(pem_text: str) -> str:
    return _openssl_x509(pem_text, "-subject", "-issuer", "-dates", "-fingerprint", "-sha256")


LEAF_HDR = [
    "; GENERATED by tools/gen-rsa-pinned-key.py -- legacy/debug leaf RSA-2048 public-key block.",
    "; Build 13 standard images ship the leaf as SEED/LEAF.DER instead of baking this block into",
    "; SEED.SYS. The 286 verifies that file against WR1 before adopting it for SKE verification.",
]
ANCHOR_HDR = [
    "; GENERATED by tools/gen-rsa-pinned-key.py --mode anchor -- the PINNED ISSUING-CA (GTS WR1)",
    "; RSA-2048 public key: the DURABLE anchor for silent auto-recertify. When the ~90-day leaf",
    "; rotates, the off-race X.509 chain-verify checks the freshly-presented leaf's signature",
    "; against THIS key (RSA-PKCS1-SHA256 over the leaf TBS) before adopting it -- so a leaf",
    "; rotation needs no rebuild, but trust still derives from an anchor we already hold.",
    "; WR1 itself lives years; RE-PIN only when WR1 rotates (a rare, human event). Regenerate:",
    ";   python3 tools/gen-rsa-pinned-key.py --mode anchor --pem <chain.pem> --out <this file>",
    ";",
    "; The on-device chain-verify copies wr1_n/r2/n0inv into the rsa_verify working constants",
    "; (rsa_one == 1 is shared) and reuses the leaf-verify scratch (rsa_sig/result/x/t) -- the",
    "; in-race leaf verify and the off-race chain-verify never run at the same time.",
]


def emit(n: int, host: str, meta: str, *, prefix: str = "rsa_", constants_only: bool = False) -> str:
    n0inv, r2 = mont_params(n)
    hdr = list(ANCHOR_HDR if prefix != "rsa_" else
               [line.replace("{host}", host) for line in LEAF_HDR])
    hdr += [";", f"; pinned {'issuer (anchor)' if constants_only else 'host'}: {host}"]
    hdr += ["; " + line for line in meta.splitlines()]
    hdr += [";"]
    if constants_only:
        hdr += [
            f"; e = 65537 (the on-device modexp hardcodes s^65537). ONLY {prefix}n is baked; the Montgomery",
            "; constants (r2, n0inv) are DERIVED at chain-verify time via rsa_adopt_derive -- this saves",
            "; ~514 B in the 286 module so the captured leaf fits the handshake-transient slot above it",
            "; (not the arena -> mid-chat recertify is safe). 128 x 16-bit little-endian limbs.",
        ]
    else:   # legacy/debug leaf mode
        hdr += [
            "; e = 65537 (the on-device modexp hardcodes s^65537). rsa_n/r2/one/n0inv are CONSTANTS",
            "; derived from the modulus; rsa_sig is the wire signature (set per handshake); the rest is",
            "; working scratch. Layout matches core/rsa_verify.inc (CIOS Montgomery, 128 x 16-bit limbs).",
        ]
    hdr += ["align 2"]
    if constants_only:   # anchor: bake only the modulus; rsa_adopt_derive computes r2 + n0inv on the fly
        body = [bignum_lines(prefix + "n", n)]
    else:
        body = [
            bignum_lines(prefix + "n", n),
            bignum_lines(prefix + "r2", r2),
            bignum_lines(prefix + "one", 1),
            f"{prefix}n0inv: dw {n0inv}\n",
            "rsa_sig: times 128 dw 0       ; the ServerKeyExchange signature (set from the wire)\n",
            "rsa_result: times 128 dw 0\n",
            "rsa_x: times 128 dw 0\n",
            "rsa_t: times 260 dw 0\n",
        ]
    return "\n".join(hdr) + "\n" + "".join(body) + "\n"


# The bench's modulus (from tools/crypto-bench/rsa_data_bench.inc rsa_n) + its known params, so we
# can prove this generator's Montgomery math reproduces the bench (n0inv=31743, the ck=54F2 setup).
_BENCH_N_WORDS = [
    31745,23358,34280,18611,30726,34904,19985,7464, 22690,55032,836,58696,47514,18934,9316,34367,
    48712,59850,38724,41412,8758,40093,34682,7979, 23131,34070,3358,36391,15109,50498,35356,9457,
    58166,3006,48479,1615,61245,54083,54900,56316, 47580,3944,30304,1782,58322,63141,38434,974,
    37364,52248,29997,17522,23180,54024,25653,58573, 19530,35414,32074,39250,43330,18195,58266,39053,
    45880,8319,6745,55569,2434,23334,36673,19486, 47635,11476,20224,44579,50510,54312,13578,39402,
    46361,22515,41760,49063,24680,27862,3540,60938, 19523,10899,51935,62537,61489,34403,6697,47558,
    3422,49454,4618,34000,23524,22701,19571,23810, 61125,30702,36724,1473,25979,11007,26839,31089,
    55260,63426,7210,12515,48173,19395,41231,9264, 59740,38607,46021,4052,32608,18910,25430,50336,
]
_BENCH_R2_WORDS = [
    31244,55623,39141,54069,64214,35693,138,33980, 21940,26722,56935,35104,3571,12097,60925,8093,
    32907,59052,38508,3057,6861,62921,23706,25150, 651,49812,47816,37152,16421,56499,61364,50659,
    7763,30247,32449,62112,43783,28982,12825,43946, 54098,56147,498,10155,22950,234,38502,45944,
    19175,16898,63411,60996,38923,40865,5215,56907, 18202,39674,60952,49861,19119,9527,4555,21763,
    54708,48255,42446,37307,64258,35371,14991,28613, 6319,603,2121,24972,52021,37233,59191,25681,
    62313,17937,57946,39844,58215,34990,13060,61730, 40128,2836,61839,11456,29027,21727,18644,33577,
    16726,61722,49904,29434,3932,30585,38601,9270, 7804,23393,47035,36213,36424,808,16270,51506,
    44826,10145,64972,57427,24368,9117,17317,24791, 17845,24839,52201,50178,39135,44677,13917,24315,
]


def _from_words(words: list[int]) -> int:
    return sum(w << (16 * i) for i, w in enumerate(words))


def selftest() -> int:
    n = _from_words(_BENCH_N_WORDS)
    n0inv, r2 = mont_params(n)
    ok_n0 = (n0inv == 31743)
    ok_r2 = (to_words(r2) == _BENCH_R2_WORDS)
    print(f"bench N0INV: got {n0inv}, expected 31743 -> {'OK' if ok_n0 else 'FAIL'}")
    print(f"bench R2 words match rsa_data_bench.inc -> {'OK' if ok_r2 else 'FAIL'}")
    return 0 if (ok_n0 and ok_r2) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["leaf", "anchor"], default="leaf",
                    help="leaf = pin the leaf key (in-race SKE verify, default); "
                         "anchor = pin the issuing CA (WR1) key for the off-race chain-verify")
    ap.add_argument("--pem", help="cert chain PEM (-showcerts); cert[0]=leaf, cert[1]=issuer (WR1)")
    ap.add_argument("--modulus", help="hex RSA modulus (alternative to --pem)")
    ap.add_argument("--cert-index", type=int,
                    help="which chain cert to pin (default 0=leaf for --mode leaf, 1=issuer for anchor)")
    ap.add_argument("--out", help="output .inc path (default: stdout)")
    ap.add_argument("--host", default="api.openai.com")
    ap.add_argument("--prefix", help="symbol prefix (default rsa_ for leaf, wr1_ for anchor)")
    ap.add_argument("--selftest", action="store_true", help="prove the Montgomery math vs the bench")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    anchor = (args.mode == "anchor")
    prefix = args.prefix or ("wr1_" if anchor else "rsa_")
    index = args.cert_index if args.cert_index is not None else (1 if anchor else 0)

    if args.modulus:
        n, meta = int(args.modulus, 16), f"modulus: (provided directly, host {args.host})"
    elif args.pem:
        pem_text = nth_cert_pem(args.pem, index)
        n, meta = modulus_from_pem_text(pem_text), cert_meta(pem_text)
    else:
        raise SystemExit("need --pem or --modulus (or --selftest)")

    text = emit(n, args.host, meta, prefix=prefix, constants_only=anchor)
    if args.out:
        with open(args.out, "w") as f:
            f.write(text)
        print(f"wrote {args.out} ({args.mode}: {n.bit_length()}-bit modulus, "
              f"prefix {prefix!r}, chain index {index})")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
