#!/usr/bin/env python3
"""Generate the pinned RSA-2048 public-key data block for the 286 secure tier.

The 286 secure tier authenticates the server by PINNING the provider's leaf RSA-2048 public
key and verifying ONLY the (mandatory) ServerKeyExchange signature against it (1 RSA verify --
fits the 6 MHz window). This script bakes a leaf modulus into the little-endian-word + Montgomery
form the on-device modexp (core/rsa_verify.inc, the bench-verified CIOS s^65537 mod N) expects:
rsa_n (modulus), rsa_r2 (R^2 mod N), rsa_one (1), rsa_n0inv (-N^-1 mod 2^16); plus the runtime
scratch (rsa_sig is the wire signature, set per handshake; rsa_result/sm/x/t are working buffers).

RE-PIN on leaf rotation (GTS leaves are ~90-day): re-run with the fresh chain. The output names
the source cert + its validity so a stale pin is obvious.

  python3 tools/gen-rsa-pinned-key.py --pem openai-chain.pem \
      --out targets/ibm_pc_5150/boot/core/rsa_pinned_key.inc --host api.openai.com
  python3 tools/gen-rsa-pinned-key.py --selftest      # prove the Montgomery math vs the bench
"""
from __future__ import annotations
import argparse
import subprocess
import sys

WORDS = 128                 # 2048-bit operands, 16-bit little-endian limbs
NBITS = WORDS * 16          # 2048
R = 1 << NBITS              # Montgomery radix


def to_words(value: int) -> list[int]:
    return [(value >> (16 * i)) & 0xFFFF for i in range(WORDS)]


def mont_params(n: int) -> tuple[int, int]:
    if n.bit_length() != 2048:
        raise SystemExit(f"modulus is {n.bit_length()} bits, expected 2048 (RSA-2048 leaf)")
    if n % 2 == 0:
        raise SystemExit("modulus is even -- not an RSA modulus")
    n0inv = (-pow(n, -1, 1 << 16)) % (1 << 16)   # -N^-1 mod 2^16  (CIOS reduction multiplier)
    r2 = pow(R, 2, n)                            # R^2 mod N
    return n0inv, r2


def bignum_lines(name: str, value: int, per_line: int = 8) -> str:
    w = to_words(value)
    out = [f"{name}:"]
    for i in range(0, WORDS, per_line):
        out.append("    dw " + ",".join(str(x) for x in w[i:i + per_line]))
    return "\n".join(out) + "\n"


def leaf_modulus_from_pem(pem_path: str) -> int:
    # The FIRST cert in a -showcerts chain is the leaf. openssl avoids a crypto-lib dependency.
    out = subprocess.run(
        ["openssl", "x509", "-in", pem_path, "-noout", "-modulus"],
        capture_output=True, text=True, check=True).stdout.strip()
    if not out.startswith("Modulus="):
        raise SystemExit(f"unexpected openssl output: {out[:40]!r}")
    return int(out[len("Modulus="):], 16)


def leaf_meta(pem_path: str) -> str:
    out = subprocess.run(
        ["openssl", "x509", "-in", pem_path, "-noout", "-subject", "-issuer", "-dates",
         "-fingerprint", "-sha256"],
        capture_output=True, text=True, check=True).stdout.strip()
    return out


def emit(n: int, host: str, meta: str) -> str:
    n0inv, r2 = mont_params(n)
    hdr = [
        "; GENERATED by tools/gen-rsa-pinned-key.py -- the PINNED leaf RSA-2048 public key for the",
        "; 286 secure tier. The server is authenticated by verifying its ServerKeyExchange signature",
        "; against THIS key (possession proof). Do not edit by hand; RE-PIN on leaf rotation:",
        ";   python3 tools/gen-rsa-pinned-key.py --pem <chain.pem> --out <this file> --host " + host,
        ";",
        f"; pinned host: {host}",
    ]
    hdr += ["; " + line for line in meta.splitlines()]
    hdr += [
        ";",
        "; e = 65537 (the on-device modexp hardcodes s^65537). rsa_n/r2/one/n0inv are CONSTANTS",
        "; derived from the modulus; rsa_sig is the wire signature (set per handshake); the rest is",
        "; working scratch. Layout matches core/rsa_verify.inc (CIOS Montgomery, 128 x 16-bit limbs).",
        "align 2",
    ]
    body = [
        bignum_lines("rsa_n", n),
        bignum_lines("rsa_r2", r2),
        bignum_lines("rsa_one", 1),
        f"rsa_n0inv: dw {n0inv}\n",
        "rsa_sig: times 128 dw 0       ; the ServerKeyExchange signature (set from the wire)\n",
        "rsa_result: times 128 dw 0\n",
        "rsa_sm: times 128 dw 0\n",
        "rsa_x: times 128 dw 0\n",
        "rsa_t: times 260 dw 0\n",
    ]
    return "\n".join(hdr) + "\n" + "".join(body) + "\n"


# The bench's modulus (from tools/crypto-bench/rsa_data_bench.inc rsa_n) + its known params, so we
# can prove this generator's Montgomery math reproduces the bench (n0inv=31743, the ck=54F2 setup).
_BENCH_N_WORDS = [
    31745,23358,34280,18611,30726,34904,19985,7464, 22690,55032,836,58696,47514,18934,9316,34367,
    48712,59850,38724,41412,8758,40093,34682,7979, 23131,34070,3358,36391,15109,50498,35356,9457,
    58166,3006,48479,1615,61245,54083,54900,56316, 47580,3944,30304,1782,58322,63141,38434,974,
    37364,52248,29997,17522,23180,54024,25653,58573, 19530,35414,32074,39250,43330,18195,58266,39053,
    45880,8319,6745,55569,2434,23334,36673,19486, 47635,11476,20224,44579,50510,54312,13578,39402,
    46361,22515,41760,49063,24680,27862,3540,60938, 19523,10899,51935,62537,61489,34403,6697,47558,
    3422,49454,4618,34000,23524,22701,19571,23810, 61125,30702,36724,1473,25979,11007,26839,31089,
    55260,63426,7210,12515,48173,19395,41231,9264, 59740,38607,46021,4052,32608,18910,25430,50336,
]
_BENCH_R2_WORDS = [
    31244,55623,39141,54069,64214,35693,138,33980, 21940,26722,56935,35104,3571,12097,60925,8093,
    32907,59052,38508,3057,6861,62921,23706,25150, 651,49812,47816,37152,16421,56499,61364,50659,
    7763,30247,32449,62112,43783,28982,12825,43946, 54098,56147,498,10155,22950,234,38502,45944,
    19175,16898,63411,60996,38923,40865,5215,56907, 18202,39674,60952,49861,19119,9527,4555,21763,
    54708,48255,42446,37307,64258,35371,14991,28613, 6319,603,2121,24972,52021,37233,59191,25681,
    62313,17937,57946,39844,58215,34990,13060,61730, 40128,2836,61839,11456,29027,21727,18644,33577,
    16726,61722,49904,29434,3932,30585,38601,9270, 7804,23393,47035,36213,36424,808,16270,51506,
    44826,10145,64972,57427,24368,9117,17317,24791, 17845,24839,52201,50178,39135,44677,13917,24315,
]


def _from_words(words: list[int]) -> int:
    return sum(w << (16 * i) for i, w in enumerate(words))


def selftest() -> int:
    n = _from_words(_BENCH_N_WORDS)
    n0inv, r2 = mont_params(n)
    ok_n0 = (n0inv == 31743)
    ok_r2 = (to_words(r2) == _BENCH_R2_WORDS)
    print(f"bench N0INV: got {n0inv}, expected 31743 -> {'OK' if ok_n0 else 'FAIL'}")
    print(f"bench R2 words match rsa_data_bench.inc -> {'OK' if ok_r2 else 'FAIL'}")
    return 0 if (ok_n0 and ok_r2) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pem", help="cert chain PEM (-showcerts); the first cert is the pinned leaf")
    ap.add_argument("--modulus", help="hex RSA modulus (alternative to --pem)")
    ap.add_argument("--out", help="output .inc path (default: stdout)")
    ap.add_argument("--host", default="api.openai.com")
    ap.add_argument("--selftest", action="store_true", help="prove the Montgomery math vs the bench")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    if args.modulus:
        n, meta = int(args.modulus, 16), f"modulus: (provided directly, host {args.host})"
    elif args.pem:
        n, meta = leaf_modulus_from_pem(args.pem), leaf_meta(args.pem)
    else:
        raise SystemExit("need --pem or --modulus (or --selftest)")

    text = emit(n, args.host, meta)
    if args.out:
        with open(args.out, "w") as f:
            f.write(text)
        print(f"wrote {args.out} ({n.bit_length()}-bit modulus, host {args.host})")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
